/* Match Signal provider-backed match-centre enrichment — PAPER ONLY. */
(function(){'use strict';
const qs=new URLSearchParams(location.search),eventId=qs.get('event_id');
const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const football={"EPL":"eng.1","La Liga":"esp.1","Bundesliga":"ger.1","Serie A":"ita.1","Ligue 1":"fra.1","Champions League":"uefa.champions","MLS":"usa.1","Primeira Liga":"por.1"};
const basketball={"NBA":"nba","WNBA":"wnba","NCAAM":"mens-college-basketball","NCAAW":"womens-college-basketball","Euroleague":"euroleague","ACB":"acb","BBL":"eng.1","BSL":"tur.1"};
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
async function prediction(){const d=await get('./data/predictions.json?v='+Date.now());return (Array.isArray(d)?d:[]).find(x=>String(x.event_id)===String(eventId));}
function cdnUrl(p){if(p.sport==='football'){const s=football[p.league];return s?'https://cdn.espn.com/core/'+s+'/game?xhr=1&gameId='+encodeURIComponent(eventId):null;}if(p.sport==='basketball'){const s=basketball[p.league]||String(p.league||'').toLowerCase().replace(/\s+/g,'-');return s?'https://cdn.espn.com/core/'+s+'/game?xhr=1&gameId='+encodeURIComponent(eventId):null;}return null;}
function rootPackage(d){return d?.gamepackageJSON||d?.gamePackageJSON||d?.gamepackage||d;}
function walk(node,out,depth){if(depth>8||node==null)return;if(Array.isArray(node)){for(const x of node)walk(x,out,depth+1);return;}if(typeof node!=='object')return;out.push(node);for(const v of Object.values(node))walk(v,out,depth+1);}
function playsFrom(root){const arrays=[];function scan(node,depth){if(depth>8||node==null)return;if(Array.isArray(node)){if(node.length&&node.some(x=>x&&typeof x==='object'&&('text' in x||'type' in x||'type_text' in x||'shooting_play' in x||'coordinate_x' in x||'coordinate_y' in x)))arrays.push(node);for(const x of node)scan(x,depth+1);return;}if(typeof node!=='object')return;for(const [k,v] of Object.entries(node)){if(/plays|playbyplay|commentary|pbp/i.test(k)&&Array.isArray(v))arrays.push(v);scan(v,depth+1);}}scan(root,0);const flat=[];for(const a of arrays)for(const x of a)if(x&&typeof x==='object'&&!flat.includes(x))flat.push(x);return flat;}
function coord(o){const c=o.coordinate||o.coordinates||o.location||o.shooting||null;let x=num(o.coordinate_x??o.coordinateX??o.x??c?.x),y=num(o.coordinate_y??o.coordinateY??o.y??c?.y);if(x===null||y===null)return null;if(x===0&&y===0)return null;return {x,y};}
function shotish(o){const t=String(o.text||o.description||o.type_text||o.typeText||o.shortText||o.type?.text||o.type?.description||'').toLowerCase();return o.shooting_play===true||o.shootingPlay===true||/shot|jump shot|three|layup|dunk|free throw|field goal|missed|made/.test(t);}
function normalize(c){let {x,y}=c;if(x>=-50&&x<=50&&y>=-50&&y<=50){x=(x+50)*1.0;y=(y+50)*1.0;}else if(x<=100&&y<=100){/* already normalized */}else return null;return {x:Math.max(2,Math.min(98,x)),y:Math.max(2,Math.min(98,y))};}
function extractShots(root){const plays=playsFrom(root),shots=[];for(const o of plays){if(!shotish(o))continue;const c=coord(o);if(!c)continue;const n=normalize(c);if(!n)continue;const made=String(o.text||o.description||o.type_text||'').toLowerCase();shots.push({x:n.x,y:n.y,made:/made|good|makes|scores|three pointer made|jump shot made/.test(made),team:o.team?.abbreviation||o.team?.displayName||o.team?.name||o.team?.shortDisplayName||o.team_id||o.teamId||'',text:o.text||o.description||o.type_text||'',clock:o.clock?.displayValue||o.clock_display_value||o.clock||'',period:o.period?.displayValue||o.period_display_value||o.period||''});}const seen=new Set();return shots.filter(s=>{const k=[s.x.toFixed(2),s.y.toFixed(2),s.clock,s.text].join('|');if(seen.has(k))return false;seen.add(k);return true;}).slice(-150);}
function extractEvents(root){const plays=playsFrom(root);return plays.map(o=>({clock:o.clock?.displayValue||o.clock_display_value||o.clock||'',period:o.period?.displayValue||o.period_display_value||o.period||'',text:o.text||o.description||o.type_text||o.shortText||o.type?.text||''})).filter(x=>x.text).slice(-40).reverse();}
function styles(){if(document.getElementById('ms-provider-style'))return;const s=document.createElement('style');s.id='ms-provider-style';s.textContent=`.msProvider{margin-bottom:16px;background:linear-gradient(145deg,#0b1730,#061023);border:1px solid #2c4b7e;border-radius:18px;padding:16px;box-shadow:0 14px 40px #0009}.msProvider h2{margin:0 0 5px;font-size:13px;text-transform:uppercase;letter-spacing:.08em;color:#c8d6f2}.msProviderSub{font-size:11px;color:#8fa5cf;margin-bottom:12px}.msShotBoard{position:relative;height:360px;border-radius:15px;overflow:hidden;border:2px solid #8bd5ff55;background:linear-gradient(90deg,#8fca72,#7dbd62);box-shadow:inset 0 0 50px #0004}.msCourt{position:absolute;inset:8px;border:2px solid #ffffffbb;border-radius:4px}.msCourt:before{content:"";position:absolute;left:50%;top:0;bottom:0;border-left:2px solid #fff8}.msCourt:after{content:"";position:absolute;left:25%;top:25%;width:50%;height:50%;border:2px solid #fff7;border-radius:50%}.msShot{position:absolute;width:10px;height:10px;border-radius:50%;transform:translate(-50%,-50%);border:2px solid #fff;box-shadow:0 0 8px #0009}.msShot.make{background:#19e6a2}.msShot.miss{background:#ff4d6d}.msShot:hover{transform:translate(-50%,-50%) scale(1.5);z-index:3}.msShotLegend{display:flex;gap:14px;flex-wrap:wrap;margin-top:9px;color:#a8b9da;font-size:11px}.msShotLegend i{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:5px}.msProviderGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.msProviderMini{background:#071025;border:1px solid #29446f;border-radius:12px;padding:11px}.msProviderMini small{display:block;color:#8fa5cf;text-transform:uppercase;font-size:10px}.msProviderMini b{display:block;margin-top:4px;font-size:16px}.msProviderEvents{max-height:260px;overflow:auto;margin-top:12px}.msProviderEvent{display:grid;grid-template-columns:70px 1fr;gap:10px;padding:9px;border-bottom:1px solid #203556;color:#d9e4f7}.msProviderEvent time{color:#ffd166;font-weight:900;font-size:11px}.msProviderNote{margin-top:10px;color:#8fa5cf;font-size:10px}.msProviderError{color:#ff8fa5;font-size:11px}.msProvider[data-sport="tennis"] .msShotBoard{display:none}@media(max-width:650px){.msShotBoard{height:280px}.msProviderGrid{grid-template-columns:1fr}}
`;document.head.appendChild(s);}
function add(root,p,shots,events){if(document.getElementById('ms-provider-panel'))return;styles();const app=document.getElementById('app');if(!app)return;const panel=document.createElement('section');panel.id='ms-provider-panel';panel.className='msProvider';panel.dataset.sport=p.sport;const shotHtml=shots.length?'<div class="msShotBoard"><div class="msCourt"></div>'+shots.map(s=>'<span class="msShot '+(s.made?'make':'miss')+'" style="left:'+s.x+'%;top:'+s.y+'%" title="'+esc((s.clock||'')+' '+(s.text||''))+'"></span>').join('')+'</div><div class="msShotLegend"><span><i style="background:#19e6a2"></i>Made</span><span><i style="background:#ff4d6d"></i>Missed/attempt</span><span>'+shots.length+' provider shot records</span></div>':'<div class="empty">No provider shot coordinates were returned for this match. Match Signal will not fabricate a shot map.</div>';
const eventHtml=events.length?events.map(x=>'<div class="msProviderEvent"><time>'+esc((x.period?' '+x.period:'')+(x.clock?' · '+x.clock:''))+'</time><div>'+esc(x.text)+'</div></div>').join(''):'<div class="empty">No provider play records returned.</div>';
panel.innerHTML='<h2>Provider match centre</h2><div class="msProviderSub">Direct ESPN game-package enrichment · '+esc(p.sport)+' · PAPER ONLY</div>'+shotHtml+'<div class="msProviderGrid"><div class="msProviderMini"><small>Provider events</small><b>'+events.length+'</b></div><div class="msProviderMini"><small>Shot coordinates</small><b>'+shots.length+'</b></div></div><div class="msProviderEvents">'+eventHtml+'</div><div class="msProviderNote">Coordinates and event records are displayed only when supplied by the provider. This layer is descriptive data, not a real-money betting instruction.</div>';const panels=[...app.querySelectorAll('.panel')];if(panels.length)panels[0].before(panel);else app.appendChild(panel);}
async function run(){if(!eventId)return;try{const p=await prediction();if(!p)return;const url=cdnUrl(p);if(!url){add(null,p,[],[]);return;}const d=await get(url);const root=rootPackage(d);const shots=p.sport==='basketball'?extractShots(root):[];const events=extractEvents(root);add(root,p,shots,events);}catch(err){console.warn('Match Signal provider enrichment failed',err);const p={sport:'unknown'};styles();const app=document.getElementById('app');if(app&&!document.getElementById('ms-provider-panel')){const panel=document.createElement('section');panel.id='ms-provider-panel';panel.className='msProvider';panel.innerHTML='<h2>Provider match centre</h2><div class="msProviderError">Provider enrichment is unavailable for this match right now. The base Match Tracker remains active.</div>';app.appendChild(panel);}}}
if(location.pathname.toLowerCase().includes('match-tracker')){const obs=new MutationObserver(()=>{if(document.querySelector('#app .hero'))run();});obs.observe(document.documentElement,{subtree:true,childList:true});setTimeout(run,1200);}
})();
