/* Match Signal Match Centre v2 — provider-first live tracker. PAPER ONLY. */
(function(){'use strict';
if(!location.pathname.toLowerCase().includes('match-tracker'))return;
const eventId=new URLSearchParams(location.search).get('event_id'); if(!eventId)return;
const football={EPL:'eng.1','La Liga':'esp.1',Bundesliga:'ger.1','Serie A':'ita.1','Ligue 1':'fra.1','Champions League':'uefa.champions',MLS:'usa.1','Primeira Liga':'por.1'};
const basketball={NBA:'nba',WNBA:'wnba',NCAAM:'mens-college-basketball',NCAAW:'womens-college-basketball',Euroleague:'euroleague',ACB:'acb',BBL:'eng.1',BSL:'tur.1'};
const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}; const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null}; const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
async function get(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function pred(){try{const d=await get('./data/predictions.json?v='+Date.now());return(Array.isArray(d)?d:[]).find(x=>String(x.event_id)===String(eventId))||null}catch(_){return null}}
function merge(e,s){if(!e&&!s)return null;const o=e?JSON.parse(JSON.stringify(e)):{};const h=s?.header?.competitions?.[0];if(h){o.competitions=o.competitions||[{}];o.competitions[0]={...o.competitions[0],...h}}if(Array.isArray(s?.plays)){o.plays=s.plays;o.details=s.plays;o.competitions=o.competitions||[{}];o.competitions[0].details=s.plays}if(s?.boxscore)o.boxscore=s.boxscore;o.__summary=!!s;return o}
async function provider(p){const sport=p?.sport||'football';if(sport==='football'){const slug=football[p.league]||'usa.1';let e=null,s=null;try{const d=await get('https://site.api.espn.com/apis/site/v2/sports/soccer/'+slug+'/scoreboard');e=(d.events||[]).find(x=>String(x.id)===String(eventId))||null}catch(_){}try{s=await get('https://site.api.espn.com/apis/site/v2/sports/soccer/'+slug+'/summary?event='+encodeURIComponent(eventId))}catch(_){}return merge(e,s)}if(sport==='basketball'){const slug=basketball[p.league]||String(p.league||'nba').toLowerCase().replace(/\s+/g,'.');let e=null,s=null;try{const d=await get('https://site.api.espn.com/apis/site/v2/sports/basketball/'+slug+'/scoreboard');e=(d.events||[]).find(x=>String(x.id)===String(eventId))||null}catch(_){}try{s=await get('https://site.api.espn.com/apis/site/v2/sports/basketball/'+slug+'/summary?event='+encodeURIComponent(eventId))}catch(_){}return merge(e,s)}for(const tour of ['atp','wta']){try{const d=await get('https://site.api.espn.com/apis/site/v2/sports/tennis/'+tour+'/scoreboard');for(const g of d.events||[])for(const z of g.groupings||[])for(const c of z.competitions||[])if(String(c.id)===String(eventId)){let s=null;try{s=await get('https://site.api.espn.com/apis/site/v2/sports/tennis/'+tour+'/summary?event='+encodeURIComponent(eventId))}catch(_){}return merge({id:eventId,name:c.name,status:c.status,competitions:[c]},s)}}catch(_){} }return null}
function cs(e){return e?.competitions?.[0]?.competitors||[]} function score(e){const c=cs(e);return{home:num(c.find(x=>x.homeAway==='home')?.score)??0,away:num(c.find(x=>x.homeAway==='away')?.score)??0}}
function rows(e){const out=[];for(const c of cs(e))for(const s of c.statistics||[])out.push({side:c.homeAway,name:String(s.displayName||s.name||s.abbreviation||''),value:String(s.displayValue??s.value??'')});if(e?.boxscore?.teams)for(const t of e.boxscore.teams||[])for(const s of t.statistics||[])out.push({side:t.homeAway,name:String(s.displayName||s.name||s.abbreviation||''),value:String(s.displayValue??s.value??'')});return out}
function stat(r,names,side){const x=r.find(v=>v.side===side&&names.some(n=>v.name.toLowerCase().replace(/[^a-z0-9]/g,'')===n.replace(/[^a-z0-9]/g,'')));if(!x)return null;const n=Number(String(x.value).replace('%','').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null}
function clock(e){return String(e?.status?.displayClock||e?.status?.clock||'')} function state(e){return String(e?.status?.type?.description||e?.status?.type?.shortDetail||e?.status?.type?.name||'')}
function fElapsed(e){const m=clock(e).match(/(\d+)(?::(\d{2}))?/);return m?clamp((Number(m[1])+Number(m[2]||0)/60)/90,0,1):.5}
function baseTotal(p){for(const x of [p?.expected_goals_total,p?.expected_total,p?.xg_total,p?.totals?.expected,p?.ou?.expected,p?.market_total]){const n=num(x);if(n!==null&&n>0&&n<8)return n}return 2.5}
function footballProb(p,e){const b=p?.probabilities||{};let h=clamp(num(b.p1)??.5,.01,.98),d=clamp(num(b.draw)??.25,.01,.98),a=clamp(num(b.p2)??.25,.01,.98);const s=score(e),m=s.home-s.away,late=clamp((fElapsed(e)-.2)/.8,0,1);if(m!==0){const k=1+late*.55;if(m>0){h*=1.35*k;a*=.58/k;d*=.78}else{a*=1.35*k;h*=.58/k;d*=.78}}const r=rows(e),hs=stat(r,['shotsontarget','sog'],'home'),as=stat(r,['shotsontarget','sog'],'away');if(hs!==null&&as!==null&&hs+as>0){const q=hs/(hs+as);h*=1+(q-.5)*.30;a*=1+((1-q)-.5)*.30}const z=h+d+a;return{home:h/z,draw:d/z,away:a/z}}
function poissonOver(lambda){let u=Math.exp(-lambda),term=u;for(let k=1;k<=2;k++){term*=lambda/k;u+=term}return clamp(1-u,0,1)}
function footballOU(p,e){const base=baseTotal(p),s=score(e),t=fElapsed(e),cur=s.home+s.away,expElapsed=base*t;let pace=expElapsed>.25?cur/expElapsed:1;pace=1+(pace-1)*(.25+.65*t);const r=rows(e),hs=stat(r,['shotsontarget','sog'],'home'),as=stat(r,['shotsontarget','sog'],'away');if(hs!==null&&as!==null)pace*=clamp(1+(((hs+as)/Math.max(.5,t*10))-1)*.06,.92,1.08);const expected=clamp(cur+base*(1-t)*clamp(pace,.65,1.45),cur,7),line=num(p?.market_total??p?.ou_line??p?.total_line)??2.5;return{expected,line,lean:expected>line+.08?'OVER':expected<line-.08?'UNDER':'NEUTRAL',over:poissonOver(expected),driver:'score + elapsed time + live tempo'}}
function bElapsed(e,p){const period=num(e?.status?.period)??1,raw=clock(e).match(/(\d+):([0-5]\d)/),rem=raw?Number(raw[1])+Number(raw[2])/60:0,total=/nba|wnba/i.test(String(p?.league||''))?48:40;return clamp(((period-1)*(total/4)+(total/4-rem))/total,0,1)}
function basketballOU(p,e){const base=baseTotal(p),s=score(e),t=bElapsed(e,p),pace=t>.05?(s.home+s.away)/t:base,w=clamp(.2+t*.85,.2,.88),expected=Math.max(s.home+s.away,base*(1-w)+pace*w),line=num(p?.market_total??p?.ou_line??p?.total_line)??base;return{expected,line,lean:expected>line+1?'OVER':expected<line-1?'UNDER':'NEUTRAL',over:null,driver:'live scoring pace + pre-match prior'}}
function tennisGames(e){let n=0;for(const c of cs(e))for(const s of c.linescores||[])n+=num(s.value)??0;return n}
function tennisOU(p,e){const cur=tennisGames(e),base=num(p?.expected_total_games??p?.expected_games??p?.totals?.expected??p?.expected_total)??22.5,sets=cs(e)[0]?.linescores?.length||0,progress=clamp(sets/3,.15,.9),expected=Math.max(cur,cur+(base-cur)*(1-progress*.55)),line=num(p?.market_total??p?.ou_line??p?.total_line)??22.5;return{expected,line,lean:expected>line+.5?'OVER':expected<line-.5?'UNDER':'NEUTRAL',over:null,driver:'current set/game state + pre-match games prior'}}
function ou(p,e){return p?.sport==='football'?footballOU(p,e):p?.sport==='basketball'?basketballOU(p,e):tennisOU(p,e)}
function removeFake(){document.querySelectorAll('.msCentre').forEach(x=>x.remove())}
function css(){if(document.getElementById('ms-v2-style'))return;const s=document.createElement('style');s.id='ms-v2-style';s.textContent='.msV2{margin:0 0 16px;padding:16px;border:1px solid #2b416d;border-radius:18px;background:linear-gradient(145deg,#0d1730,#081126);box-shadow:0 14px 40px #0009}.msV2 h2{margin:0 0 12px;font-size:13px;color:#c8d6f2;text-transform:uppercase;letter-spacing:.07em}.msV2grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.msV2box{background:#071025;border:1px solid #2a416d;border-radius:12px;padding:11px}.msV2box small{display:block;color:#9eb0d4;text-transform:uppercase;font-size:10px}.msV2box b{display:block;margin-top:4px;font-size:18px}.msV2ou{margin-top:12px;border:1px solid #2b416d;border-radius:14px;padding:12px;background:#071025}.msV2ou strong{font-size:22px}.msV2oug{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:9px}.msV2oug div{background:#0a142a;border-radius:10px;padding:8px}.msV2oug small{display:block;color:#9eb0d4;font-size:9px;text-transform:uppercase}.msV2oug b{display:block;margin-top:2px}.msV2events{max-height:260px;overflow:auto;margin-top:12px}.msV2event{padding:9px 10px;border-bottom:1px solid #203556;font-size:12px}.msV2event time{color:#ffd166;font-weight:900;margin-right:10px}.msV2note{margin-top:10px;color:#9eb0d4;font-size:11px}.ok{color:#19e6a2}.warn{color:#ffd166}.bad{color:#ff4d6d}@media(max-width:700px){.msV2grid,.msV2oug{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function updateProbs(p,e){if(p.sport!=='football')return;const v=footballProb(p,e),a=[v.home,v.draw,v.away],cards=[...document.querySelectorAll('#app .prob')];cards.slice(0,3).forEach((c,i)=>{const b=c.querySelector('.probHead b'),f=c.querySelector('.fill');if(b)b.textContent=Math.round(a[i]*100)+'%';if(f)f.style.width=Math.round(a[i]*100)+'%'})}
function render(p,e){css();removeFake();updateProbs(p,e);const app=document.getElementById('app');if(!app)return;document.getElementById('ms-v2')?.remove();const s=score(e),r=rows(e),t=ou(p,e),c=cs(e),events=(Array.isArray(e.plays)?e.plays:Array.isArray(e.details)?e.details:[]).map(x=>({time:x.clock?.displayValue||x.clock||x.period?.displayValue||x.period||'',text:String(x.text||x.shortText||x.description||x.type?.text||x.type?.description||'')})).filter(x=>x.text).slice(-18).reverse();const ev=events.length?events.map(x=>'<div class="msV2event"><time>'+esc(x.time||'LIVE')+'</time>'+esc(x.text)+'</div>').join(''):'<div class="msV2note">No detailed provider play-by-play returned. Score and clock tracking remain active.</div>';const hn=c.find(x=>x.homeAway==='home')?.team?.displayName||c.find(x=>x.homeAway==='home')?.athlete?.displayName||p.player_1||'Home',an=c.find(x=>x.homeAway==='away')?.team?.displayName||c.find(x=>x.homeAway==='away')?.athlete?.displayName||p.player_2||'Away';const hs=stat(r,['shotsontarget','sog'],'home'),as=stat(r,['shotsontarget','sog'],'away');const panel=document.createElement('section');panel.id='ms-v2';panel.className='msV2';panel.innerHTML='<h2>Corrected live tracker</h2><div class="msV2grid"><div class="msV2box"><small>Current score</small><b>'+esc(hn)+' '+s.home+'–'+s.away+' '+esc(an)+'</b></div><div class="msV2box"><small>Provider state</small><b>'+esc(state(e))+'</b></div><div class="msV2box"><small>Live statistics</small><b>'+r.length+'</b></div><div class="msV2box"><small>Provider enrichment</small><b class="'+(e.__summary?'ok':'warn')+'">'+(e.__summary?'ENRICHED':'SCOREBOARD ONLY')+'</b></div></div><div class="msV2ou"><small style="color:#9eb0d4;text-transform:uppercase">Live expected O/U</small><div><strong>'+t.expected.toFixed(2)+'</strong> projected final · line '+t.line.toFixed(1)+' · <b class="'+(t.lean==='OVER'?'ok':t.lean==='UNDER'?'bad':'warn')+'">'+t.lean+'</b></div><div class="msV2oug"><div><small>Driver</small><b>'+esc(t.driver)+'</b></div><div><small>Over probability</small><b>'+(t.over==null?'Not shown':'~'+Math.round(t.over*100)+'% heuristic')+'</b></div><div><small>Shots on target</small><b>'+(hs==null&&as==null?'Unavailable':(hs??'—')+' – '+(as??'—'))+'</b></div><div><small>Data quality</small><b>'+r.length+' fields</b></div></div><div class="msV2note">Dynamic state projection. PAPER ONLY — UNVALIDATED. No fabricated pressure, shot map, player positions, or bookmaker line.</div></div><h2 style="margin-top:16px">Recent provider events</h2><div class="msV2events">'+ev+'</div><div class="msV2note">Provider data is authoritative for score/clock. Probabilities and O/U are research projections and remain disabled for real-money execution.</div>';const anchor=document.getElementById('ms-provider-live')||document.getElementById('ms-live-trace')||app.querySelector('.panel');if(anchor)anchor.after(panel);else app.appendChild(panel)}
async function run(){try{const p=await pred();if(!p)return;const e=await provider(p);if(e)render(p,e)}catch(err){console.debug('tracker v2',err)}}
run();setInterval(run,10000);
})();
