function headers(){return {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}}
const API='https://api.livetennisapi.com/api/public/v1';
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function tokens(v){return new Set(norm(v).split(/\s+/).filter(Boolean))}
function scoreName(x){return x?.name||x?.display_name||x?.displayName||x?.player?.name||x?.player?.display_name||x?.athlete?.displayName||x?.competitor?.name||''}
function players(m){const out=[];for(const key of ['players','competitors','participants']){if(Array.isArray(m?.[key]))out.push(...m[key].map(scoreName).filter(Boolean))}for(const key of ['player1','player2','home','away']){const n=scoreName(m?.[key]);if(n)out.push(n)}return [...new Set(out)]}
function samePlayer(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return false;let hits=0;for(const t of A)if(B.has(t))hits++;return hits>=Math.min(2,A.size,B.size)}
function findMatch(rows,p1,p2){return rows.find(m=>{const ns=players(m);return ns.some(n=>samePlayer(n,p1))&&ns.some(n=>samePlayer(n,p2))})||null}
function currentState(m){const s=m?.score||m?.live_score||m?.current_score||m?.state?.score||{};return {sets:s.sets||s.set_scores||m?.sets||null,games:s.games||s.game_scores||m?.games||null,points:s.points||s.point_scores||m?.points||null,server:s.server??s.serving_player??m?.server??null,is_tiebreak:s.is_tiebreak??s.tiebreak??m?.is_tiebreak??false,timestamp:s.timestamp||m?.updated_at||m?.timestamp||null,status:m?.status||m?.event_status||'live'} }
export async function onRequestGet(context){const key=context.env.LIVE_TENNIS_API_KEY;if(!key)return new Response(JSON.stringify({ok:false,error:'LIVE_TENNIS_API_KEY_NOT_CONFIGURED'}),{status:503,headers:headers()});const u=new URL(context.request.url),p1=u.searchParams.get('player1')||'',p2=u.searchParams.get('player2')||'',tour=(u.searchParams.get('tour')||'').toLowerCase();if(!p1||!p2)return new Response(JSON.stringify({ok:false,error:'PLAYER_NAMES_REQUIRED'}),{status:400,headers:headers()});try{const url=new URL(API+'/matches');url.searchParams.set('status','live');if(['atp','wta','challenger','itf','juniors'].includes(tour))url.searchParams.set('tour',tour);const r=await fetch(url,{headers:{'X-API-Key':key,'Authorization':`Bearer ${key}`,Accept:'application/json'},cache:'no-store'});const text=await r.text();if(!r.ok)return new Response(JSON.stringify({ok:false,error:`LIVE_TENNIS_HTTP_${r.status}`,body_prefix:text.slice(0,180)}),{status:r.status,headers:headers()});let data;try{data=JSON.parse(text)}catch{return new Response(JSON.stringify({ok:false,error:'LIVE_TENNIS_NON_JSON'}),{status:502,headers:headers()})}const rows=Array.isArray(data?.data)?data.data:Array.isArray(data?.matches)?data.matches:Array.isArray(data)?data:[];const match=findMatch(rows,p1,p2);if(!match)return new Response(JSON.stringify({ok:false,error:'MATCH_NOT_FOUND_IN_LIVE_TENNIS_FEED',searched:{player1:p1,player2:p2,tour:tour||'all'}}),{status:404,headers:headers()});return new Response(JSON.stringify({ok:true,provider:'Live Tennis API',match_id:match.id||match.match_id||null,players:players(match),state:currentState(match),raw_updated_at:new Date().toISOString()}),{headers:headers()})}catch(e){return new Response(JSON.stringify({ok:false,error:'LIVE_TENNIS_FETCH_FAILED',detail:String(e?.message||e)}),{status:502,headers:headers()})}}
